apiVersion: v1
kind: Service
metadata:
  name: pps-rtp-service
  namespace: ppswork
spec:
  type: NodePort
  selector:
    app: pps-rtp
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000

